// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace HansKindberg.VisualStudio.Extensions.TextFormatter
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		#region Fields

		public static Guid PackageGuid = new Guid(PackageGuidString);
		public static Guid CommandSetGuid = new Guid(CommandSetGuidString);
		public const string CommandSetGuidString = "d743086e-39e2-43be-9fce-80f59e3854d2";
		public static Guid ImageGuid = new Guid(ImageGuidString);
		public const string ImageGuidString = "0bffb789-0c25-4702-8e8c-b3f9ce2d1d81";
		public const string PackageGuidString = "9fcb72ab-03fa-418e-bbfc-61021c68288c";

		#endregion
	}

	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		#region Fields

		public const int CommandId = 0x0002;
		public const int GroupId = 0x0001;

		#endregion
	}
}