// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace HansKindberg.VisualStudio.Extensions.TextFormatter
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		#region Fields

		public static Guid CommandGuid = new Guid(CommandGuidString);
		public const string CommandGuidString = "d743086e-39e2-43be-9fce-80f59e3854d2";
		public static Guid PackageGuid = new Guid(PackageGuidString);
		public const string PackageGuidString = "9fcb72ab-03fa-418e-bbfc-61021c68288c";

		#endregion
	}

	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		#region Fields

		public const int DefaultButtonId = 0x0001;
		public const int DefaultGroupId = 0x0002;
		public const int GroupId = 0x0003;
		public const int ItemsButtonId = 0x0004;
		public const int ItemsGroupId = 0x0005;
		public const int JsonMenuId = 0x0006;
		public const int MenuGroupId = 0x0007;
		public const int MenuId = 0x0008;
		public const int XmlMenuId = 0x0009;

		#endregion
	}
}