// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace HansKindberg.VisualStudio.Extensions.TextFormatter
{
	internal sealed partial class Vsix
	{
		#region Fields

		public const string Author = "Hans Kindberg - open source";
		public const string Description = @"Support for formatting text-files. For the moment support for json- and xml-files.";
		public const string Id = "196879b0-7392-4cb0-a29a-51090fbb2274";
		public const string Language = "en-US";
		public const string Name = "Hans Kindberg - Text formatter";
		public const string Tags = "format, formatter, formatting, json, json-formatter, xml, xml-formatter";
		public const string Version = "1.0.0";

		#endregion
	}
}